blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://canonical.com/multipass/docs
    about: See here about potential solutions to some common problems
  - name: Forums
    url: https://discourse.ubuntu.com/c/multipass
    about: Please ask and answer questions here.
  - name: "#multipass on Libera.Chat"
    url: https://web.libera.chat/?channels=#multipass
    about: Chat to us!
